import { Providers } from "@/redux/provider/privider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function StayLayout({ children }) {
  return (
    <Providers>
      <section>{children}</section>
    </Providers>
  );
}
